<template>
  <svg
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 250 250"
    version="1.1"
    fill="url(#linearGradient)"
  >
    <g
      fill="#FF16D7"
    >
      <g
        transform="translate(85 66)"
        fill="#FFE547"
      >
        <ellipse
          opacity=".244"
          cx="66.5"
          cy="67.5"
          rx="66.5"
          ry="67"
        />
        <circle
          cx="67"
          cy="67.5"
          r="34"
        />
      </g>
      <g
        transform="translate(0 67)"
        fill="#FF16D7"
      >
        <ellipse
          opacity=".244"
          cx="66.5"
          cy="66.5"
          rx="66.5"
          ry="67"
        />
        <circle
          cx="67"
          cy="66.5"
          r="34"
        />
      </g>
      <g
        transform="translate(42)"
        fill="#86D600"
      >
        <ellipse
          opacity=".244"
          cx="66.5"
          cy="67.5"
          rx="66.5"
          ry="67"
        />
        <circle
          cx="67"
          cy="67.5"
          r="34"
        />
      </g>
    </g>
  </svg>
</template>

<style lang="stylus" scoped>
.current-color
  fill: currentColor
</style>
